#!/bin/sh -ue

# This script installs Nix package manager inside a Termux installation.
# Copyright (c) 2019 Alexander Sosedkin <monk@unboiled.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Based off the official Nix install script (https://nixos.org/nix/install),
# presumably written by Eelco Dolstra.


# This script installs Nix package manager inside a Termux installation.
# It does not require root, user namespaces or disabling SELinux,
# but it relies on proot and numerous hacks instead.
# Only tested with aarch64, may also accidentally work on x86.

# Usage:
# * Install and run Termux
# * Execute this script inside Termux

# Careful, this is carelessly written alpha-quality stuff.


PLAYGROUND="$HOME/.nix"
DIVE_SCRIPT="$PLAYGROUND/nix-powered"
TERMUX_BIN="/data/data/com.termux/files/usr/bin"



oops() {
    echo "$0:" "$@" >&2
    exit 1
}


if [ ! -x "$DIVE_SCRIPT" ]; then
	echo "removing the previous installation..."
	chmod -R 700 "$PLAYGROUND" || true
	rm -rf "$PLAYGROUND" || oops "failed to remove $PLAYGROUND"
	mkdir -p "$PLAYGROUND" || oops "failed to create $PLAYGROUND"

	echo "installing tools..."
	pkg in -y proot bzip2 tar wget || oops "failed to install required tools"

	tmpDir="$PLAYGROUND/tmp"
	mkdir -p "$tmpDir" || oops "false to create $tmpDir"

	echo "preparing mock /nix and /etc..."
	mkdir "$PLAYGROUND/nix" || oops "failed to create $PLAYGROUND/nix"
	mkdir "$PLAYGROUND/etc" || oops "failed to create $PLAYGROUND/etc"
	echo 'nameserver 1.1.1.1' > "$PLAYGROUND/etc/resolv.conf" || oops "failed to create $PLAYGROUND/etc/resolv.conf"
	mkdir "$PLAYGROUND/etc/nix/" || oops "failed to create $PLAYGROUND/etc/nix"
	# https://github.com/NixOS/nix/issues/2632#issuecomment-457610729
	echo 'sandbox = false' > "$PLAYGROUND/etc/nix/nix.conf" || oops "failed to create $PLAYGROUND/etc/nix/nix.conf"

	case "$(uname -s).$(uname -m)" in
	    Linux.x86_64)
	        hash=0ff23ac8437c5d15d08063a0b677c47639ab291988ec95eb603f29dc237eb00b
	        path=i71d2zyp9c30v98mvqc4dvmnvb1sbx90/nix-2.23.3-x86_64-linux.tar.xz
	        system=x86_64-linux
	        ;;
	    Linux.i?86)
	        hash=b417445a9d0091507a38f5321c4711d9f2a862061347596f13ab9dcbafcaf15b
	        path=z201kfh4cab9n36hpg3b708bk15aqi55/nix-2.23.3-i686-linux.tar.xz
	        system=i686-linux
	        ;;
	    Linux.aarch64)
	        hash=4d75ef8049ed2cef54dc6b6a40115010fc7773544c10904e198248ed9b6c4b4a
	        path=gqlsjys012rw36hmljv5f2jav8y0c4kx/nix-2.23.3-aarch64-linux.tar.xz
	        system=aarch64-linux
	        ;;
	    Linux.armv6l)
	        hash=8e706706cb7c27a3aca33ec82afb3bc383eac633ad99857380008f7be2193849
	        path=pv3rz6nqq5sd3r42h1fm58z0jpzy4rwc/nix-2.23.3-armv6l-linux.tar.xz
	        system=armv6l-linux
	        ;;
	    Linux.armv7l)
	        hash=c0988eb62334b7736f0ef60b767465f681c0f622b4635b4450436d127239b866
	        path=1y8i52p9m7v2lqh3gpq1mjllzbnnghfm/nix-2.23.3-armv7l-linux.tar.xz
	        system=armv7l-linux
	        ;;
	    Linux.riscv64)
	        hash=ca8758fe631781d4b94af5c60f482d5a6d8279c0f20d85213233447ed6916773
	        path=g8ywv3b9binpnhxkp5lv0v60v2kx5jdr/nix-2.23.3-riscv64-linux.tar.xz
	        system=riscv64-linux
	        ;;
	    Darwin.x86_64)
	        hash=2bfa2564bc7814336935155d093653ecd4392239df07df46093b0188a2d1acea
	        path=chv9j1lfr92jsy5y12icd6arhsil0fd8/nix-2.23.3-x86_64-darwin.tar.xz
	        system=x86_64-darwin
	        ;;
	    Darwin.arm64|Darwin.aarch64)
	        hash=af5370b63fdc0c8009ad42446dfc46ad347855fc89256b86b5080ac04c89828f
	        path=8jlzxrnl7zfk04r0q1hczr3fpylkwah5/nix-2.23.3-aarch64-darwin.tar.xz
	        system=aarch64-darwin
	        ;;
	    *) oops "sorry, there is no binary distribution of Nix for your platform";;
	esac

	url=https://releases.nixos.org/nix/nix-2.23.3/nix-2.23.3-$system.tar.xz

	tarball=$tmpDir/nix-2.23.3-$system.tar.xz

	echo "downloading Nix 2.23.3 binary tarball for $system from '$url' to '$tmpDir'..."
	$TERMUX_BIN/wget "$url" -O "$tarball" || oops "failed to download '$url'"

	hash2="$(sha256sum -b "$tarball" | cut -c1-64)"

	if [ "$hash" != "$hash2" ]; then
		oops "SHA-256 hash mismatch in '$url'; expected $hash, got $hash2"
	fi

	echo "unpacking $tarball..."
	unpack=$tmpDir/unpack
	mkdir -p "$unpack"
	cleanup() {
		rm -rf "$unpack"
	}
	trap cleanup EXIT INT QUIT TERM
	< "$tarball" xzcat | $TERMUX_BIN/tar -xf - -C "$unpack" || oops "failed to unpack $tarball"

	script=$(echo "$unpack"/*/install)

	[ -e "$script" ] || oops "installation script is missing from the binary tarball!"

	INTERMEDIATE_SCRIPT="$tmpDir/intermediate_install_script"
	{
########
	cat > "$INTERMEDIATE_SCRIPT" << --------EOF
	export USER=\$(whoami)
	export NIX_INSTALLER_NO_MODIFY_PROFILE=true
	unset LD_LIBRARY_PATH
	unset LD_PRELOAD
	$script "\$@"
--------EOF
	} || oops "failed to create $INTERMEDIATE_SCRIPT"

	chmod +x "$INTERMEDIATE_SCRIPT" || oops "failed to chmod +x $INTERMEDIATE_SCRIPT"

	echo "running Nix install script in proot..."
	proot \
		-b "$PLAYGROUND/nix:/nix" \
		-b "$PLAYGROUND/etc:/etc" \
		--link2symlink \
		"$INTERMEDIATE_SCRIPT" || oops "failed to run Nix install script in proot"

	echo "creating $DIVE_SCRIPT and finalizing the installation..."
	{
########
	cat > "$DIVE_SCRIPT" << --------EOF
	#!/bin/sh -e
	export PS1="nix-powered> "
	export USER=$(whoami)
	unset LD_LIBRARY_PATH
	unset LD_PRELOAD
	echo Termux PATH \$PATH
	TERMUX_PATH="\$PATH"
	. \$HOME/.nix-profile/etc/profile.d/nix.sh
	export PATH=\${PATH%":\$TERMUX_PATH"}
	"\$@"
--------EOF
	} || oops "failed to create $DIVE_SCRIPT"
	chmod +x "$DIVE_SCRIPT" || oops "failed to chmod +x $DIVE_SCRIPT"

	echo "installation is completed."

	echo "to reinstall, rm -r \"$PLAYGROUND\" and re-run the script"
fi


proot \
	-b "$PLAYGROUND/nix:/nix" \
	-b "$PLAYGROUND/etc:/etc" \
	-b "/etc:/android-etc" \
	--link2symlink \
	"$DIVE_SCRIPT" "$@"
